<?php return [
    [
        'id' => 1,
        'name' => 'Новый',
        'description' => '',
        'color' => 'dark',
        'email_user' => 0,
        'email_manager' => 1,
        'subject_user' => '',
        'subject_manager' => 'app_ecomm_order_status_1_manager_email_subject',
        'body_user' => '',
        'body_manager' => '@FILE chunks/emails/order/status/manager.tpl',
        'active' => 1,
        'final' => 0,
        'fixed' => 1,
        'rank' => 0,
        'editable' => 1
    ], [
        'id' => 2,
        'name' => 'Принят в обработку',
        'description' => '',
        'color' => '000000',
        'email_user' => 1,
        'email_manager' => 0,
        'subject_user' => 'app_ecomm_order_status_2_email_subject',
        'subject_manager' => '',
        'body_user' => '@FILE chunks/emails/order/status/user.tpl',
        'body_manager' => '',
        'active' => 1,
        'final' => 0,
        'fixed' => 1,
        'rank' => 1,
        'editable' => 1
    ], [
        'id' => 3,
        'name' => 'Передан на доставку',
        'description' => '',
        'color' => '000000',
        'email_user' => 1,
        'email_manager' => 0,
        'subject_user' => 'app_ecomm_order_status_3_email_subject',
        'subject_manager' => '',
        'body_user' => '@FILE chunks/emails/order/status/user.tpl',
        'body_manager' => '',
        'active' => 1,
        'final' => 0,
        'fixed' => 1,
        'rank' => 2,
        'editable' => 1
    ], [
        'id' => 4,
        'name' => 'Отменен',
        'description' => '',
        'color' => '000000',
        'email_user' => 1,
        'email_manager' => 1,
        'subject_user' => 'app_ecomm_order_status_4_email_subject',
        'subject_manager' => 'app_ecomm_order_status_4_manager_email_subject',
        'body_user' => '@FILE chunks/emails/order/status/user.tpl',
        'body_manager' => '@FILE chunks/emails/order/status/manager.tpl',
        'active' => 1,
        'final' => 1,
        'fixed' => 1,
        'rank' => 3,
        'editable' => 1
    ], [
        'id' => 5,
        'name' => 'Выполнен',
        'description' => '',
        'color' => '000000',
        'email_user' => 1,
        'email_manager' => 0,
        'subject_user' => 'app_ecomm_order_status_5_email_subject',
        'subject_manager' => '',
        'body_user' => '@FILE chunks/emails/order/status/user.tpl',
        'body_manager' => '',
        'active' => 1,
        'final' => 1,
        'fixed' => 1,
        'rank' => 4,
        'editable' => 1
    ],
];