<?php return [
    [
        'id' => 1,
        'name' => 'Наличными',
        'description' => 'В офисе Компании - пос. Смирновка',
        'price' => 0,
        'logo' => 'assets/tpl/images/logo.png',
        'rank' => 0,
        'active' => 1,
        'class' => '',
        'properties' => '',
        'idx' => 1,
        'link' => '',
    ],
    [
        'id' => 2,
        'name' => 'Картой',
        'description' => 'Оплата картой при получении/выдачи товара',
        'price' => 0,
        'logo' => '',
        'rank' => 0,
        'active' => 1,
        'class' => '',
        'properties' => '',
        'idx' => 2,
        'link' => '',
    ],
    [
        'id' => 3,
        'name' => 'Безнал расчет',
        'description' => 'На расчетный счет Компании по реквизитам',
        'price' => 0,
        'logo' => '/assets/components/mspreceiptaccount/sh.png',
        'rank' => 0,
        'active' => 1,
        'class' => '',
        'properties' => '',
        'idx' => 3,
        'link' => '',
    ]
];

