<?php return [
    [
        'id' => 2,
        'car_id' => 2,
        'zone_id' => 1,
        'price' => 0.00,
        'fixprice' => 3800.00,
        'minprice' => 0.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 3,
        'car_id' => 2,
        'zone_id' => 2,
        'price' => 0.00,
        'fixprice' => 3800.00,
        'minprice' => 0.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 5,
        'car_id' => 3,
        'zone_id' => 1,
        'price' => 0.00,
        'fixprice' => 10000.00,
        'minprice' => 0.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 6,
        'car_id' => 3,
        'zone_id' => 2,
        'price' => 330.00,
        'fixprice' => 0.00,
        'minprice' => 10000.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 8,
        'car_id' => 2,
        'zone_id' => 3,
        'price' => 150.00,
        'fixprice' => 0.00,
        'minprice' => 8000.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 9,
        'car_id' => 3,
        'zone_id' => 3,
        'price' => 180.00,
        'fixprice' => 0.00,
        'minprice' => 15000.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 10,
        'car_id' => 4,
        'zone_id' => 1,
        'price' => 0.00,
        'fixprice' => 3300.00,
        'minprice' => 0.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 11,
        'car_id' => 4,
        'zone_id' => 2,
        'price' => 180.00,
        'fixprice' => 0.00,
        'minprice' => 3000.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 12,
        'car_id' => 4,
        'zone_id' => 3,
        'price' => 120.00,
        'fixprice' => 0.00,
        'minprice' => 4000.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 14,
        'car_id' => 4,
        'zone_id' => 4,
        'price' => 0.00,
        'fixprice' => 3300.00,
        'minprice' => 0.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 16,
        'car_id' => 4,
        'zone_id' => 5,
        'price' => 150.00,
        'fixprice' => 0.00,
        'minprice' => 4000.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 17,
        'car_id' => 2,
        'zone_id' => 5,
        'price' => 160.00,
        'fixprice' => 0.00,
        'minprice' => 5000.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 18,
        'car_id' => 2,
        'zone_id' => 4,
        'price' => 0.00,
        'fixprice' => 3800.00,
        'minprice' => 3000.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 19,
        'car_id' => 3,
        'zone_id' => 5,
        'price' => 330.00,
        'fixprice' => 0.00,
        'minprice' => 12000.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 20,
        'car_id' => 3,
        'zone_id' => 4,
        'price' => 0.00,
        'fixprice' => 10000.00,
        'minprice' => 0.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 33,
        'car_id' => 6,
        'zone_id' => 1,
        'price' => 0.00,
        'fixprice' => 1350.00,
        'minprice' => 0.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 34,
        'car_id' => 6,
        'zone_id' => 2,
        'price' => 120.00,
        'fixprice' => 0.00,
        'minprice' => 1500.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 35,
        'car_id' => 6,
        'zone_id' => 3,
        'price' => 120.00,
        'fixprice' => 0.00,
        'minprice' => 2500.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 36,
        'car_id' => 6,
        'zone_id' => 4,
        'price' => 0.00,
        'fixprice' => 1350.00,
        'minprice' => 0.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ], [
        'id' => 37,
        'car_id' => 6,
        'zone_id' => 5,
        'price' => 120.00,
        'fixprice' => 0.00,
        'minprice' => 2000.00,
        'maxprice' => 0.00,
        'freefrom' => 0.00,
        'notprice' => 0,
        'rank' => 0,
    ]
];